global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "admin-panel-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'admin-panel-backend'
    static_configs:
      - targets: ['backend:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'admin-panel-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 15s