http:
  routers:
    dashboard:
      rule: Host(`traefik.crm-synergy.ru`)
      entryPoints:
        - websecure
      middlewares:
        - https-redirect
      tls:
        certResolver: letsencrypt
      service: api@internal

    frontend:
      rule: Host(`app.crm-synergy.ru`)
      entryPoints:
        - websecure
      middlewares:
        - https-redirect
      tls:
        certResolver: letsencrypt
      service: frontend

    backend:
      rule: Host(`api.crm-synergy.ru`)
      entryPoints:
        - websecure
      middlewares:
        - https-redirect
      tls:
        certResolver: letsencrypt
      service: backend

    email-service:
      rule: Host(`email.crm-synergy.ru`)
      entryPoints:
        - websecure
      middlewares:
        - https-redirect
      tls:
        certResolver: letsencrypt
      service: email-service

    telegram-service:
      rule: Host(`telegram.crm-synergy.ru`)
      entryPoints:
        - websecure
      middlewares:
        - https-redirect
      tls:
        certResolver: letsencrypt
      service: telegram-service

    # Redirect HTTP to HTTPS
    dashboard-redirect:
      rule: Host(`traefik.crm-synergy.ru`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: api@internal

    frontend-redirect:
      rule: Host(`app.crm-synergy.ru`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: frontend

    backend-redirect:
      rule: Host(`api.crm-synergy.ru`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: backend

    email-service-redirect:
      rule: Host(`email.crm-synergy.ru`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: email-service

    telegram-service-redirect:
      rule: Host(`telegram.crm-synergy.ru`)
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: telegram-service

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8080"

    email-service:
      loadBalancer:
        servers:
          - url: "http://email-service:8081"

    telegram-service:
      loadBalancer:
        servers:
          - url: "http://telegram-service:8082"