http:
  routers:
    traefik:
      rule: "Host(`traefik.crm-synergy.ru`)"
      entryPoints:
        - websecure
      service: traefik
      tls:
        certResolver: letsencrypt

    backend-api:
      rule: "Host(`app.crm-synergy.ru`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: backend
      tls:
        certResolver: letsencrypt
      priority: 10

    backend:
      rule: "Host(`api.crm-synergy.ru`)"
      entryPoints:
        - websecure
      service: backend
      tls:
        certResolver: letsencrypt

    frontend:
      rule: "Host(`app.crm-synergy.ru`) && !PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: frontend
      tls:
        certResolver: letsencrypt
      priority: 5

    email-service:
      rule: "Host(`email.crm-synergy.ru`)"
      entryPoints:
        - websecure
      service: email-service
      tls:
        certResolver: letsencrypt

    telegram-service:
      rule: "Host(`telegram.crm-synergy.ru`)"
      entryPoints:
        - websecure
      service: telegram-service
      tls:
        certResolver: letsencrypt

  services:
    traefik:
      loadBalancer:
        servers:
          - url: "http://traefik:8080"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8084"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    email-service:
      loadBalancer:
        servers:
          - url: "http://email-service:8081"

    telegram-service:
      loadBalancer:
        servers:
          - url: "http://telegram-service:8082"

# Removed strip prefix middleware to keep `/api` segment for backend routes
# End of file